on:
  pull_request:
  push:
    branches: [develop]
  release:
    types: [published]
jobs:
  build_container:
    runs-on: ubuntu-latest
    name: build docker container
    steps:
      - name: Get Docker Image Tag
        id: get_image_tag
        run: |
          REGISTRY=docker.pkg.github.com
          DOCKER_IMAGE=${REGISTRY}/apiobuild/post-it-pad/post-it-pad
          VERSION=edge
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          if [ "${{ github.event_name }}" = "push" ]; then
            TAGS="$TAGS"
          fi
          echo ::set-output name=registry::${REGISTRY}
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          buildkitd-flags: --debug
      - name: Login in to registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: build and publish docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: ${{ steps.get_image_tag.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.get_image_tag.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
          # push: ${{ startsWith(github.ref, 'refs/tags/') ||  startsWith(github.ref, 'refs/heads/develop') }}
          push: true
